# -*- coding: utf-8 -*-
"""datacleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aoGBLMDyDS7b8sVMBtvgSABK_3GmedV9
"""

import pandas as pd

df = pd.read_excel('scraping olx.xlsx')

df

df = df.rename(columns={'Product Name' : 'Type'})

df[['Year', 'Kilometres']] = df['Year-km'].str.split('-', n=1, expand=True)

df

df['Kilometres'] = df['Kilometres'].str.replace(' km', '')

df['Kilometres'] = df['Kilometres'].str.replace(r'(\d+)-(\d+)', r'\1 - \2')

df['Year'] = df['Year'].str.replace(' ', '')
df['Year'] = df['Year'].str.replace('<', '')

df = df.drop('Year-km', axis=1)

df

df['Locations'].unique()

df['Locations'] = df['Locations'].str.replace('Hari ini', '').str.replace('hari yang lalu', '').str.replace('Kemarin', '')

df['Locations'] = df['Locations'].str.replace(r'\d+ ', '', regex=True)

df['Locations'].unique()

df['Locations'] = df['Locations'].str.replace(r'(Mar|Feb|Des|Jan)$', '', regex=True)

df['Locations'].unique()

df

df.isnull().sum()